name: Jenkins Plugin CI/CD

on:
  workflow_dispatch:

env:
  ARTIFACTORY_USER: ${{secrets.ARTIFACTORY_USER}}
  ARTIFACTORY_SECRET: ${{secrets.ARTIFACTORY_SECRET}}

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build
        id: build
        run: ./build.sh
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: hpi
          path: ./job-dsl-plugin/build/libs/job-dsl.hpi

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Publish to Artifactory
        run: ./publish.sh ${{ needs.ci.outputs.version }}
